# compose file for defining redis-stack service
version: "3"

services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - ~/redis_data:/data
  minio:
    image: minio/minio
    volumes:
      - ~/minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}}
    volumes:
      - ~/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  # separation-worker-1:
  #   build:
  #     context: ../../separation-worker
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5999:5999" # Adjust port as necessary
  #   depends_on:
  #     - redis
  #     - minio
  #     - postgres
  #   environment:
  #     MODELS_DIR: ${MODELS_DIR}
  #     REDIS_HOST: ${REDIS_HOST}
  #     REDIS_PORT: ${REDIS_PORT}
  #     MINIO_ENDPOINT: ${MINIO_ENDPOINT}
  #     MINIO_PORT: ${MINIO_PORT}
  #     MINIO_DEFAULT_BUCKET: ${MINIO_DEFAULT_BUCKET}
  #     MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
  #     MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
  #     DATABASE_URL: ${DATABASE_URL}
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]
volumes:
  redis-data:
  minio_data:
  postgres_data:
